version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20  # Specify the Node.js version you want
    commands:
      - echo "Installing dependencies..."
      - npm install   # if you have a package.json
  pre_build:
    commands:
      - echo "Pre-build phase..."
  build:
    commands:
      - echo "Running the script..."
      - node index.js   # Replace 'index.js' with your actual file name
  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - '**/*'
  discard-paths: yes
