version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install"
  build:
    commands:
      - echo "Running the script..."
      - node demo.js   # change to your actual filename
  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - '**/*'
  discard-paths: yes

